### ISSUE TITLE
Add support for URLs and ISBNs to resources

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#11]

**Comment by wooorm** [comment]
@Razpudding What do you think, Is this essential (a bug) or an enhancement?

**Comment by Razpudding** [comment]
I think it's an enhancement. We can definitely live without for a while.

**Comment by wooorm** [comment]
Done in cmd-curriculum-form@next, it’s awesome! Automated citing!

**Comment by Razpudding** [comment]
W00t I'm excited to try this out.
