### ISSUE TITLE
Rethink profiling term: -> deepening

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#12]
Profiling sounds too much like what the 👮🏽‍♀️ do

**Comment by Razpudding** [comment]
How about specialization?

**Comment by wooorm** [comment]
I really like that!
It does have a slightly different meaning I think: “profiling” as a term includes someone focussing on all three of tech, visual, and interaction. But specialisation doesn’t perfectly capture that.
Deepening isn’t nice either 🤔
Maybe we can ask Charlie?

**Comment by Razpudding** [comment]
You're right. How about 'developing' . Actually, I'd rather have it be: foundation, development, minor, graduation.

**Comment by wooorm** [comment]
I found that HvA’s official Dutch-English terms list uses “specialisation” for “profileren”.
