### ISSUE TITLE
Add local storage so input is saved

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide-frontend-input#13]
Filling in this form might take a lot of time if teachers have to find pieces of info somewhere. It would be awful if you lost what you filled in because you closed the page or navigated away.

This could be solved using local storage. We'd prob have to ask the user if they want to continue where they left off if they revisit the page. Also it would be a good idea to wipe the local storage when the data is sent to the database correctly.

**Comment by wooorm** [comment]
I think what we do here is based on whether we want an OK solution, or a great one. This would be an OK one, and LDAP + user accounts + drafts + edit would be the great one. Both could work, maybe also together. But depends on the needs of humans.

**Comment by wooorm** [comment]
No longer needed in cmd-curriculum-form@next as nothing’s required anymore.
