### ISSUE TITLE
We need a way to limit who can fill in which module.

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide-frontend-input#14]
This is a tricky one without user management but we probably want to keep teachers from filling in the wrong modules.
We can prob do without this feature for a while.

**Comment by wooorm** [comment]
This relates a bit to GH-13.

I think in the end, the flow would be something where year managers create “proposals” for courses with only a tiny bit of info (name, year, quarter, credits). They send these proposals to a coordinators (or they actually send a list of proposals to a list of coordinators).

A human (multiple?) with a role “coordinator” is thus “assigned” to a module. And there’s a due date to when it needs to be submitted. Other people could also be assigned to the module as a reviewers, with different roles (teacher, editor, roosteraar?) and they would have different rights (read, suggest, or write?).

I think when a module is submitted, it’s “locked” after the due date. After that, changes could still be proposed, but specific people (currcomm) would need to accept/reject the proposed changes.

...anyway, just some ideas on how I think it *should* go in a far, far future.

**Comment by wooorm** [comment]
cmd-curriculum-api@next crawls a Google Sheet where managers and coordinators propose courses and fill in the bare minimum of them. That info is used to set up SIS. And it also populates a database.
Later coordinators fill out more info for those modules through the cmd-curriculum-form.

This issue still stands for the “rights” and “locked” part, but the proposal phase is included in next.

**Comment by wooorm** [comment]
Tracked elsewhere.
