### ISSUE TITLE
We need to be able to deal with multiple entries for one module

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide-frontend-input#15]
If a teacher fills in a module and someone else fills in the same module later, will it show up as double in the database?
The best fix would be to show a user if a module has already been filled in with the same characteristics as the one they are currently filling in. Same year, same name (although that might have to be a fuzzy logic check) and to ask them if they want to overwrite or update that module.

**Comment by wooorm** [comment]
In the end I believe coordinators don’t pick a name (or some of the other essentials), but they’ll have to choose from a list of possible things they have the rights for the fill in.

**Comment by wooorm** [comment]
I think teachers/coordinators will also have an overview of “their” courses.

And I like the fuzzy search thing. More as a “Clippy” that says “Oh, looks like students read this tutorial already in a previous course Y”.

**Comment by Razpudding** [comment]
Omg yes let's bring back clippy!!!

And yeah makes sense they'd pick from a list of options but that sounds quite far into the future while this issue is something I see happening soon.

**Comment by wooorm** [comment]
This is solved because it’s no longer possible to add new courses, just to PATCH them, in cmd-curriculum-form@next.
