### ISSUE TITLE
Teachers need to be able to see which modules already exist.

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide-frontend-input#16]
A teacher needs to be able to see a module they've already filled in. In case they want to update it.
But you also want a view where you can see which modules have already been created. This would be important for administrators who ask teachers to fill in modules. But also to have a good overview of which modules exist and which info they have. It would be kind of weird to go through the dashboard to select that module.

**Comment by wooorm** [comment]
Relates to GH-13 and GH-14.

**Comment by wooorm** [comment]
Solved because it’s no longer possible to add new courses in cmd-curriculum-form@next.
