### ISSUE TITLE
Methods question bug: tested methods are required

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide-frontend-input#17]
Selecting at least one method to be 'tested' is required. That should not be the case.

**Comment by Razpudding** [comment]
Both 'gebruikt' and 'tested' are required. Either neither should be required or there should be a "not applicable" option.

**Comment by wooorm** [comment]
Is it actually weird? I mean. Don’t courses always have methods?

Relates to GH-10.

**Comment by Razpudding** [comment]
Nope, they don't. Methods is something we want teachers to use (especially the curcom) but some courses might not use any. Besides teachers are free to say none apply to their course. So yeah relates to issue #10

**Comment by wooorm** [comment]
Fixed in cmd-curriculum-form@next.
