### ISSUE TITLE
Scrolling doesn't work correctly

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide-frontend-input#19]
"There’s also this bug that when you go to the next section it scrolls down. You wont see that youve missed questions untill you try to submit that section"
The last part is the real issue. Users might not notice they've missed any questions and this become frustrated.

**Comment by wooorm** [comment]
Solution would be to scroll to top (`window.scrollTo(0, 0)` I believe or so?) in [`next`](https://github.com/cmda-the-lab/study-guide-frontend-input/blob/d43a9e0afb24af0cc47e0c6191758074e9934d28/src/App.vue#L1420)

**Comment by wooorm** [comment]
Fixed in cmd-curriculum-form@next.
