### ISSUE TITLE
Change phase, learning year, quarter, and clusters

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#2]
...so that it’s impossible/hard to fill in wrong info.

**Comment by Razpudding** [comment]
I see what you mean. They're all interrelated and it would make sense to have one question that helps define the info behind these fields. 
For instance, if you could see a diagra of the current curriculum and then click where this module would fall, the output might be [year 2], [quarter 2], [cluster:'blok web'] with the option to override each field to allow for things like a course being taught in year 2 and 3.

**Comment by wooorm** [comment]
done in cmd-curriculum-form@next (going to close it here though, as for security reasons that repo isn’t online).
