### ISSUE TITLE
Add descriptions for module type field: project vs course

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#3]
I’ve pinged David about this.

**Comment by Razpudding** [comment]
Good luck! There's different definitions that refer to things that actually ARE different that are all called "project" right now.  Even if we change it in our app it'll need a lot of explanation for coordinators to get what the new terms mean. Blegh human language[.](https://en.wikipedia.org/wiki/Lojban)

**Comment by wooorm** [comment]
I think the language is super weird.
One important part is *why* do they want to know the difference? Some fields are for projects, others for courses. Why is that distinction even made?

Anyway, I asked around a bit, and nobody has a clear answer...

**Comment by Razpudding** [comment]
It's not really about the distinction I think. It's more that people need to be able to call a cluster of modules something and they decided to go with "project" which is incorrect. A module that is very practical like 'Project 2' in the first year is also called "project" but there it's a more apt description.
The third year "projects" might as well be called 'cluster' or 'blok'; they certainly aren't projects. To make matters worse, these third year "projects" have a module within them that actually is a project and is called such.
Untill teachers stop calling both types 'project' our form will remain to be confusing.

An additional issue is that the curcom seems to want to know different things about projects than about courses. The bad part about that is that they consider both types of "projects" mentioned above to be of the same nature for some vague reason 🤷🏼‍♂️

**Comment by wooorm** [comment]
done in cmd-curriculum-form@next I think.
