### ISSUE TITLE
Fix performance issues

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#7]
Maybe this is only in development, but the app is a bit slow.

**Comment by Razpudding** [comment]
I had similar issues! Prob good to run some diagnostics when you release this for production.

**Comment by wooorm** [comment]
Fixed by removing vue material and going vanilla. Super fast. In cmd-curriculum-form@next.

**Comment by Razpudding** [comment]
Lol, can't believe it ended up being pure javascript 😆 
I guess we weren't using the component system all that much anyway but would love to know which patterns you ended up using!
