### ISSUE TITLE
Add sorting to all API datasets

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#8]
Currently only humans are sorted, the others should too.

**Comment by Razpudding** [comment]
As this is an issue in the frontend app, do you mean sorting API data when it arrives at the frontend? If not, please move it to the API.

**Comment by wooorm** [comment]
Yes, yes, and not needed!

**Comment by wooorm** [comment]
(API sorting is nice but optional, feel free to open an issue as well if you think that makes sense)
