### ISSUE TITLE
Bug: there’s an empty human at the end

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-frontend-input#9]

**Comment by Razpudding** [comment]
Don't worry, all coders feel that way at the end of the day.
...
Do elaborate.

**Comment by wooorm** [comment]
<img width="441" alt="screenshot 2018-12-11 at 10 29 00" src="https://user-images.githubusercontent.com/944406/49790901-959a2e80-fd2f-11e8-90e1-cad9a9d23830.png">
<img width="825" alt="screenshot 2018-12-11 at 10 29 15" src="https://user-images.githubusercontent.com/944406/49790917-9d59d300-fd2f-11e8-9cb1-d5b25974d64a.png">

**Comment by Razpudding** [comment]
Intriguing 👀

**Comment by wooorm** [comment]
Definitely a coder 😉

**Comment by Razpudding** [comment]
Fixed :)
